CREATE TABLE "Names" (
	"ID"	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	"Name"	TEXT NOT NULL
);

CREATE TABLE "Birthday" (
	"ID"	INTEGER NOT NULL,
	"Day"	INTEGER NOT NULL,
	"Month"	INTEGER NOT NULL,
	"Notes"	TEXT,
	"Secret"	TEXT,
	FOREIGN KEY("ID") REFERENCES "Name"("ID"),
	PRIMARY KEY("ID")
);